name: Code quality checks

on:
  pull_request:
  push:

jobs:
  check-newlines:
    name: Check for CRLF and final newlines
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '.github/workflows/') ||
      contains(github.event.head_commit.message, 'src/') ||
      contains(github.event.head_commit.message, '.clang-format')
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/check-newlines.sh

  check-formatting:
    name: Check for consistent formatting
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '.github/workflows/') ||
      contains(github.event.head_commit.message, 'src/') ||
      contains(github.event.head_commit.message, '.clang-format')
    strategy:
      matrix:
        path:
          - check: 'src'
            exclude: 'sdk'
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}

  check-quotes:
    name: Check quotes in translations
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'translations/') ||
      contains(github.event.head_commit.message, '.github/workflows/')
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/check-quotes.sh